ipm_image_node:
  ros__parameters:
    output_frame: "base_footprint"
    type: "mask"
    scale: 1.0
    use_distortion: false
    plane_coefficients: [0.0, 0.0, 1.0, 0.230]
    border_size: 5
    kernel_size: 3