/entrance_exploration_action_server:
  ros__parameters:
    osm_file_path: '/path/to/your/map.osm'
    exploration_radius: 2.0
    exploration_points: 5
    camera_topic: '/camera_sensor/image_raw'
    map_frame: 'map'
    odom_frame: 'lidar_odom' 